# Import Data

In [35]:
import pandas as pd
from pathlib import Path

df = pd.read_csv('data/ClaMP_Integrated-5184.csv').drop(['packer_type'], axis=1)
print(df.shape)
df.head()
#TO DO: process packer type column

(5210, 69)

,e_cblp,e_cp,e_cparhdr,e_maxalloc,e_sp,e_lfanew,NumberOfSections,CreationYear,FH_char0,FH_char1,...,LoaderFlags,sus_sections,non_sus_sections,packer,E_text,E_data,filesize,E_file,fileinfo,class
0,144,3,4,65535,184,256,4,1,0,1,...,1,1,3,0,6.603616,5.443362,1181520,6.627552,1,0
1,144,3,4,65535,184,184,4,1,0,1,...,1,1,3,0,5.205926,2.123522,7680,5.318221,0,0
2,144,3,4,65535,184,272,5,1,0,1,...,1,1,4,0,6.238000,3.380859,57872,6.507758,1,0
3,144,3,4,65535,184,184,1,1,0,1,...,1,0,1,0,0.000000,0.000000,95616,4.575092,1,0
4,144,3,4,65535,184,224,5,1,0,1,...,1,1,4,0,6.355626,0.702621,48128,5.545531,1,0

# Split Data

In [36]:
from sklearn.model_selection import train_test_split
y = df.pop('class')
X = df.copy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

# ML Classification

In [37]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer, accuracy_score
import winsound
#TO DO: add other models, add bayesian search

# Pipeline

In [38]:
scoring = make_scorer(accuracy_score)
scaler = StandardScaler()
pipeline = Pipeline(steps=[("scaler", scaler), ('clf', None)])

In [39]:
param_grid = [
    {
        "clf": [SVC()],
        "clf__kernel": ["rbf", "poly", "sigmoid"],
        "clf__gamma": [1, 0.1, 0.01, 0.001],
        "clf__C": [0.1, 1, 10, 100],
    }
]

# Grid Search

In [40]:
grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    cv=5,
    verbose=1,
    scoring="accuracy",
)

In [41]:
grid_search.fit(X_train, y_train)
winsound.Beep(500, 1000)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

# Results

In [42]:
columns = ['params', 'mean_test_score', 'mean_fit_time', 'std_test_score']
cv_df = pd.DataFrame(grid_search.cv_results_).sort_values(by='rank_test_score')[columns].reset_index(drop=True)
cv_df = cv_df.join(cv_df.pop('params').apply(pd.Series))
cv_df.clf = cv_df.clf.apply(lambda x: x.__str__().split('(')[0].replace('Classifier', '')).astype("category")
cv_df.head(10)

,mean_test_score,mean_fit_time,std_test_score,clf,clf__C,clf__gamma,clf__kernel
0,0.978648,0.142212,0.005382,SVC,1.0,0.10,poly
1,0.976969,0.146619,0.003964,SVC,100.0,0.01,rbf
2,0.974809,0.157617,0.003122,SVC,10.0,0.01,rbf
3,0.973131,0.270497,0.005848,SVC,10.0,0.10,rbf
4,0.972891,0.225053,0.006589,SVC,100.0,0.10,rbf
5,0.971931,0.291408,0.005901,SVC,1.0,0.10,rbf
6,0.969771,0.116600,0.005739,SVC,10.0,0.10,poly
7,0.969531,0.198403,0.003595,SVC,0.1,0.10,poly
8,0.969531,0.150106,0.003595,SVC,100.0,0.01,poly
9,0.966890,0.138015,0.009524,SVC,0.1,1.00,poly

# Plots (TBC)

In [43]:
#TO DO: plot confusion matrix